### ISSUE TITLE
1.0.0 tag is not part of crystal-devel branch (or any other branch)

### ISSUE THREAD

**Issue by cottsay** [ros-visualization/rqt_py_console#6]
The `1.0.0` tag that was released with Crystal doesn't appear in any branches. At present, it should be part of `crystal-devel`, but that branch appears to have the same commit at HEAD with a different commit ID.

**Comment by realdream** [comment]
I found that too. which cause `vcs export` failed with:

> src/ros-visualization/rqt_py_console: Could not determine remote containing '2ab8356f46d073e48f38cba11668118317007a39'

**Comment by dirk-thomas** [comment]
I change the 1.0.0 tag to point to the commit on the crystal-devel branch. It seems two different versions of the changelog have been pushed.

@mlautman FYI
